import {readFile,writeFile,mkdir,stat,chmod,rm,realpath,rename,copyFile} from 'node:fs/promises';
import {resolve,join,dirname,relative,sep} from 'node:path';
import {homedir} from 'node:os';
import {fileURLToPath} from 'node:url';
import {createServer} from 'node:http';
import {spawn} from 'node:child_process';
import {randomUUID} from 'node:crypto';
import {validateManifest,inspectGLB,validPath,sha256,canonicalJSON,verifyTile,starterGLB} from '../sdk/index.js';
const version='0.5.0',argv=process.argv.slice(2),command=argv.shift()||'help',opts={},args=[];
const boolean=new Set(['json','no-open','help']);
const valued=new Set(['registry','kind','tile','variant','rotation','name','title','port','export','as','version']);
for(let i=0;i<argv.length;i++){const a=argv[i];if(!a.startsWith('--'))args.push(a);else {const key=a.slice(2);if(boolean.has(key))opts[key]=true;else if(valued.has(key)&&argv[i+1]&&!argv[i+1].startsWith('--'))opts[key]=argv[++i];else throw Error(`Unknown option or missing value: ${a}`);}}
const registry=String(opts.registry||process.env.THREETOPIA_REGISTRY||'https://creators.threetopia.com').replace(/\/$/,'');
const ru=new URL(registry);if(ru.username||ru.password||ru.pathname!=='/'||ru.search||ru.hash||ru.protocol!=='https:'&&!(ru.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(ru.hostname)))throw Error('Registry must be an HTTPS origin (or HTTP localhost for development).');
const configDir=process.env.THREETOPIA_HOME||join(homedir(),'.config','threetopia'),configPath=join(configDir,'credentials.json'),runtime=resolve(dirname(fileURLToPath(import.meta.url)),'../runtime');
const readJSON=async file=>JSON.parse(await readFile(file,'utf8'));
const exists=async p=>{try{await stat(p);return true;}catch{return false;}};
async function credentials(){try{return await readJSON(configPath);}catch(e){if(e.code==='ENOENT')return {};throw Error('Could not read CLI credentials. Check the config file.');}}
async function saveCredentials(value){await mkdir(configDir,{recursive:true,mode:0o700});await writeFile(configPath,JSON.stringify(value,null,2)+'\n',{mode:0o600});await chmod(configPath,0o600);}
async function api(path,{method='GET',body,raw,authenticated=true}={}){const config=authenticated?await credentials():{},secret=config[registry]?.token;if(authenticated&&!secret)throw Error('Log in first: threetopia login');const response=await fetch(`${registry}/api${path}`,{method,redirect:'error',headers:{...(secret?{Authorization:`Bearer ${secret}`}:{ }),...(body?{'Content-Type':'application/json'}:{ }),...(raw?{'Content-Type':'application/octet-stream'}:{})},body:raw||body&&JSON.stringify(body),signal:AbortSignal.timeout(90000)});const data=await response.json();if(!response.ok)throw Error(data.message+(data.details?'\n'+data.details.join('\n'):''));return data;}
async function download(id,ver,file){const config=await credentials(),secret=config[registry]?.token,r=await fetch(`${registry}/api/packages/${id}/versions/${ver}/files?path=${encodeURIComponent(file.path)}`,{redirect:'error',headers:secret?{Authorization:`Bearer ${secret}`}:{},signal:AbortSignal.timeout(90000)});if(!r.ok)throw Error(`Could not download ${file.path}.`);const data=new Uint8Array(await r.arrayBuffer());if(data.length!==file.bytes||await sha256(data)!==file.sha256)throw Error(`Integrity check failed: ${file.path}.`);return data;}
function within(root,path){if(!validPath(path))throw Error(`Unsafe path: ${path}`);const out=resolve(root,path),rel=relative(root,out);if(rel.startsWith('..'+sep)||rel==='..'||rel.startsWith(sep))throw Error('Files must stay in the project.');return out;}
async function safeRead(root,path){const file=within(root,path),actual=await realpath(file),base=await realpath(root);if(!actual.startsWith(base+sep))throw Error(`Symlinks outside the project are not allowed: ${path}`);return new Uint8Array(await readFile(actual));}
async function project(root){const config=await readJSON(join(root,'threetopia.json'));if(config.registry!==registry)throw Error(`This project uses ${config.registry}. Use --registry ${config.registry}`);return config;}
async function check(root){const cfg=await project(root),manifest=structuredClone(cfg.manifest);manifest.files=[];const files=new Map();for(const path of cfg.files||[]){const data=await safeRead(root,path);files.set(path,data);manifest.files.push({path,bytes:data.length,sha256:await sha256(data)});}if(manifest.kind==='world'){manifest.tile=await readJSON(join(root,'tile.lock.json'));if(!await verifyTile(manifest.tile))throw Error('The host tile was modified. Restore tile.lock.json from your reservation.');}
  const errors=await validateManifest(manifest);if(errors.length)throw Error(errors.join('\n'));const report={};
  for(const [path,data] of files){const roles=manifest.kind==='world'?Object.entries(manifest.content).filter(([,p])=>p===path).map(([r])=>r):path.endsWith('.glb')?['asset']:[];for(const role of roles)report[role]=inspectGLB(data,role,manifest.tile);}
  return {cfg,manifest,files,report};
}
async function createFiles(root,pkg,contract,manifest=null,downloadFiles=[]){
  await mkdir(root,{recursive:false});
  try{
    let files;
    if(manifest&&downloadFiles.length){files=downloadFiles.map(f=>f.path);for(const f of downloadFiles){const path=within(root,f.path);await mkdir(dirname(path),{recursive:true});await writeFile(path,await download(pkg.id,manifest.version,f));}}
    else {const isWorld=pkg.kind==='world';files=isWorld?['content/world.glb','content/map.glb','content/overview.glb']:['assets/beacon.glb'];await mkdir(join(root,isWorld?'content':'assets'));
      for(const path of files)await writeFile(join(root,path),starterGLB((path.includes('world.glb')?33.333333:1)*Math.min(1,(contract?.slot?.regions?.[0]?.radius??190)/60)));
      manifest={schemaVersion:1,name:pkg.name,version:'0.1.0',kind:pkg.kind,title:pkg.title||pkg.name.split('/')[1],description:pkg.description||'',license:'MIT',changelog:'Initial version.',dependencies:{},...(isWorld?{tile:contract,content:{world:'content/world.glb',map:'content/map.glb',overview:'content/overview.glb'}}:{exports:{model:'assets/beacon.glb'}})};
    }
    const {files:hashes,...editable}=manifest;await writeFile(join(root,'threetopia.json'),JSON.stringify({registry,packageId:pkg.id,projectId:randomUUID(),manifest:editable,files},null,2)+'\n');
    if(pkg.kind==='world')await writeFile(join(root,'tile.lock.json'),JSON.stringify(contract,null,2)+'\n');
    await writeFile(join(root,'.gitignore'),'threetopia_modules/\ndist-threetopia/\n');
    await writeFile(join(root,'README.md'),`# ${manifest.title}\n\n${manifest.kind==='world'?'The reserved Threetopia host tile is immutable. Replace the three GLBs in content/. World coordinates are metres, map coordinates use scale 0.03. Content starts at local y=0, with x/z relative to tile.lock.json slot.origin. Every triangle must fit in one locked build region; paths and water stay clear. Do not change tile.lock.json.':'Replace the assets and update the named exports in threetopia.json. Add every distributed file to the files list.'}\n\n- threetopia check\n- threetopia preview\n- threetopia install @threetopia/beacon\n- threetopia push (private preview)\n- threetopia publish (public release)\n\nUpdate manifest.version and manifest.changelog for every release.\n\nDocumentation: https://docs.threetopia.com\n`);
    return root;
  }catch(e){throw Error(`Project setup could not finish: ${e.message}. Your remote package is saved; remove the incomplete directory and run threetopia clone ${pkg.name}.`);}
}
async function ownByName(name){const {packages}=await api('/packages?mine=1'),p=packages.find(p=>p.name===name);if(!p)throw Error('Package not found in your account. Use threetopia install for another creator’s package.');return (await api(`/packages/${p.id}`));}
const print=v=>console.log(opts.json?JSON.stringify(v,null,2):typeof v==='string'?v:JSON.stringify(v,null,2));
function help(){console.log(`Threetopia CLI ${version}\n\nAccount\n  login [--no-open]                 Approve your CLI in a browser\n  logout                           Revoke this CLI token\n  whoami                           Show the signed-in creator\n\nTiles and projects\n  tiles [--json]                    Connected coordinates and compatible Wang layouts\n  reserve q,r --variant bay-coast --rotation 0    Reserve a fixed host tile first\n  create <dir> --kind world --tile <reservation-id>\n  create <dir> --kind asset\n  clone @creator/package [dir]      Download your package and locked tile\n\nDevelop and release\n  check [dir]                       Measure geometry and enforce budgets\n  preview [dir] [--port 5195]        Local interactive world/map preview\n  build [dir]                       Build a portable preview directory\n  push [dir]                        Upload a private, validated version\n  publish [dir]                     Publish an already-validated version\n\nReuse\n  search [query]                    Find published packages\n  install @creator/name[@1.0.0]     Download, verify and record installation\n  uninstall @creator/name          Remove it from this project's lockfile\n  use @creator/name --export model --as map|world|overview\n                                   Copy an installed GLB into world content\n\nSet --registry <origin> for a development registry. Project data: threetopia.json.\nDocs: https://docs.threetopia.com/cli`);}
async function previewBuild(root,output){const checked=await check(root);await mkdir(output,{recursive:true});for(const f of ['index.html','preview.js','registry-host.worker.js','THREE-LICENSE.txt'])await copyFile(join(runtime,f),join(output,f));await writeFile(join(output,'preview.json'),JSON.stringify({manifest:checked.manifest,report:checked.report}));for(const [path,data] of checked.files){const dest=within(join(output,'files'),path);await mkdir(dirname(dest),{recursive:true});await writeFile(dest,data);}return checked;}
async function install(name){const root=resolve('.'),cfg=await project(root),spec=name?.match(/^(@[^/]+\/[^@]+)(?:@(.+))?$/);if(!spec)throw Error('Use @creator/package or @creator/package@1.2.3.');
  const lockPath=join(root,'threetopia-lock.json'),lock=await exists(lockPath)?await readJSON(lockPath):{version:1,registry,projectId:cfg.projectId,packages:{}};if(lock.registry!==registry||lock.projectId!==cfg.projectId)throw Error('Lockfile belongs to a different registry or project.');
  const resolved=new Map(),visiting=new Set();async function resolvePackage(n,v){if(visiting.has(n))throw Error('Circular package dependency.');const old=resolved.get(n);if(old){if(v!=='latest'&&old.version!==v)throw Error(`Conflicting dependency versions: ${n}`);return;}if(resolved.size>=64)throw Error('Dependency tree is too large.');visiting.add(n);const p=await api(`/resolve?name=${encodeURIComponent(n)}&version=${encodeURIComponent(v)}`);resolved.set(n,p);for(const [dn,dv] of Object.entries(p.manifest.dependencies||{}))await resolvePackage(dn,dv);visiting.delete(n);}
  await resolvePackage(spec[1],spec[2]||'latest');for(const [n,v] of Object.entries(cfg.manifest.dependencies||{}))if(n!==spec[1])await resolvePackage(n,v);const staging=join(root,`.threetopia-install-${randomUUID()}`);await mkdir(staging);
  try{for(const [n,p] of resolved){const base=within(staging,n.replace('@',''));for(const f of p.files){const dest=within(base,f.path);await mkdir(dirname(dest),{recursive:true});await writeFile(dest,await download(p.package.id,p.version,f));}await writeFile(join(base,'package.threetopia.json'),JSON.stringify(p.manifest,null,2));}
    for(const [n,p] of resolved){const dest=within(join(root,'threetopia_modules'),n.replace('@',''));await mkdir(dirname(dest),{recursive:true});await rm(dest,{recursive:true,force:true});await rename(within(staging,n.replace('@','')),dest);lock.packages[n]={packageId:p.package.id,version:p.version,files:p.files,manifest:p.manifest,directory:relative(root,dest)};}
    cfg.manifest.dependencies={...cfg.manifest.dependencies};if(resolved.get(spec[1]).manifest.kind==='asset')cfg.manifest.dependencies[spec[1]]=resolved.get(spec[1]).version;await writeFile(join(root,'threetopia.json'),JSON.stringify(cfg,null,2)+'\n');await writeFile(lockPath,JSON.stringify(lock,null,2)+'\n');
    for(const [n,p] of resolved){await api(`/packages/${p.package.id}/install`,{method:'POST',body:{version:p.version,projectId:cfg.projectId}});console.log(`✓ ${n}@${p.version} installed and verified.`);}
  }finally{await rm(staging,{recursive:true,force:true});}
}
try{
  if(command==='help'||opts.help){help();}
  else if(command==='--version'||command==='version'){console.log(version);}
  else if(command==='login'){
    const grant=await api('/auth/device',{method:'POST',body:{},authenticated:false});console.log(`Open ${grant.verificationUri}\nConfirm code ${grant.userCode} in your browser.`);
    if(!opts['no-open']){const cmd=process.platform==='darwin'?'open':process.platform==='win32'?'rundll32':'xdg-open',a=process.platform==='win32'?['url.dll,FileProtocolHandler',grant.verificationUri]:[grant.verificationUri];spawn(cmd,a,{stdio:'ignore',detached:true}).on('error',()=>{}).unref();}
    const deadline=Date.now()+grant.expiresIn*1000;let signed=false;
    while(Date.now()<deadline){await new Promise(r=>setTimeout(r,grant.interval*1000));const result=await api('/auth/device/poll',{method:'POST',body:{deviceCode:grant.deviceCode},authenticated:false});if(result.status==='approved'){const config=await credentials();config[registry]={token:result.accessToken,creator:result.creator.handle,expiresAt:Date.now()+result.expiresIn*1000};await saveCredentials(config);console.log(`Signed in as @${result.creator.handle}.`);signed=true;break;}}
    if(!signed)throw Error('Login request expired. Run threetopia login again.');
  }else if(command==='logout'){await api('/auth/logout',{method:'POST',body:{}});const cfg=await credentials();delete cfg[registry];await saveCredentials(cfg);console.log('Signed out. The CLI token has been revoked.');}
  else if(command==='whoami'){const {creator}=await api('/me');if(!creator)throw Error('Please log in again.');print(creator);}
  else if(command==='tiles'){const data=await api('/tiles');if(opts.json)print(data);else {for(const s of data.slots.filter(s=>s.status!=='occupied'))console.log(`(${s.q}, ${s.r})  ${s.status}`);if(opts.json!==true)console.log('Use the choices on each coordinate from threetopia tiles --json, including rotation.');console.log(`\n${data.variants.length} styled layouts: ${data.variants.map(v=>v.id).join(', ')}\n\nChoose visually: ${registry}/tiles`);}}
  else if(command==='reserve'){const [q,r]=String(args[0]||'').split(',').map(Number);const data=await api('/tiles/reserve',{method:'POST',body:{q,r,variant:opts.variant,rotation:Number(opts.rotation||0)}});print(data);if(!opts.json)console.log(`Next: threetopia create my-world --kind world --tile ${data.id}`);}
  else if(command==='create'){
    if(!args[0])throw Error('Choose a new project directory.');const root=resolve(args[0]);if(await exists(root))throw Error('The project directory already exists.');const {creator}=await api('/me');if(!creator?.handle)throw Error('Choose your handle on the creator website.');const kind=opts.kind||'world';if(!['world','asset'].includes(kind))throw Error('--kind must be world or asset.');
    const tile=kind==='world'?opts.tile?await api(`/tiles/${opts.tile}`):null:null;if(kind==='world'&&!tile)throw Error('Choose a tile first: threetopia tiles, then threetopia reserve q,r --variant bay-coast --rotation 0.');
    const slug=root.split(sep).pop(),name=opts.name||`@${creator.handle}/${slug}`,title=opts.title||slug.split('-').map(s=>s[0]?.toUpperCase()+s.slice(1)).join(' '),pkg=await api('/packages',{method:'POST',body:{name,kind,title,description:'',tileId:tile?.id}});
    await createFiles(root,{...pkg,title},tile?.contract);console.log(`Created ${name}\ncd ${args[0]}\nthreetopia preview`);
  }else if(command==='clone'){
    const data=await ownByName(args[0]),root=resolve(args[1]||args[0].split('/')[1]);if(await exists(root))throw Error('Target directory already exists.');const v=data.versions.find(v=>['ready','published'].includes(v.state));await createFiles(root,data.package,data.tile?.contract,v?.manifest,v?.manifest.files);console.log(`Cloned ${data.package.name} to ${root}.\nRun threetopia preview from that directory.`);
  }else if(['check','build','preview','push','publish'].includes(command)){
    const root=resolve(args[0]||'.');
    if(command==='publish'){const cfg=await project(root),result=await api(`/packages/${cfg.packageId}/versions/${cfg.manifest.version}/publish`,{method:'POST',body:{}});print({state:result.state,url:`${registry}/packages/${cfg.packageId}`});}
    else if(command==='check'){const c=await check(root);print({valid:true,package:c.manifest.name,version:c.manifest.version,metrics:c.report});}
    else if(command==='push'){const c=await check(root);const reservation=await api(`/packages/${c.cfg.packageId}`);if(c.manifest.kind==='world'&&canonicalJSON(reservation.tile.contract)!==canonicalJSON(c.manifest.tile))throw Error('The local tile does not match your server reservation.');
      await api(`/packages/${c.cfg.packageId}/versions`,{method:'POST',body:c.manifest});for(const [path,data] of c.files){await api(`/packages/${c.cfg.packageId}/versions/${c.manifest.version}/files?path=${encodeURIComponent(path)}`,{method:'PUT',raw:data});console.log(`Uploaded ${path}`);}const result=await api(`/packages/${c.cfg.packageId}/versions/${c.manifest.version}/validate`,{method:'POST',body:{}});print({state:result.state,preview:`${registry}/preview/${c.cfg.packageId}/${c.manifest.version}`,metrics:result.report.metrics});console.log('Private preview ready. Publish from Threetopia Creators or run threetopia publish.');}
    else if(command==='build'){const output=join(root,'dist-threetopia');await rm(output,{recursive:true,force:true});await previewBuild(root,output);console.log(`Built portable preview: ${output}`);}
    else {const port=Number(opts.port||5195);if(!Number.isInteger(port)||port<1024||port>65535)throw Error('--port must be 1024–65535.');await check(root);const server=createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost'),p=decodeURIComponent(u.pathname);if(req.method!=='GET')throw Error();let content,type='application/octet-stream';if(p==='/'||p==='/index.html'){content=await readFile(join(runtime,'index.html'));type='text/html';}else if(p==='/THREE-LICENSE.txt'){content=await readFile(join(runtime,'THREE-LICENSE.txt'));type='text/plain';}else if(p==='/preview.js'||p==='/registry-host.worker.js'){content=await readFile(join(runtime,p.slice(1)));type='text/javascript';}else if(p==='/preview.json'){const c=await check(root);content=JSON.stringify({manifest:c.manifest,report:c.report});type='application/json';}else if(p.startsWith('/files/')){const c=await check(root);content=c.files.get(p.slice(7));if(!content)throw Error();}else throw Error();res.writeHead(200,{'Content-Type':type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(content);}catch{res.writeHead(404);res.end('Not found or invalid project. Run threetopia check.');}});server.on('error',e=>{console.error(e.message);process.exitCode=1;});server.listen(port,'127.0.0.1',()=>console.log(`Preview: http://127.0.0.1:${port}/\nRefresh after editing. Ctrl+C to stop.`));}
  }else if(command==='search'){const data=await api(`/packages?q=${encodeURIComponent(args.join(' '))}`,{authenticated:false});print(data.packages.map(p=>({name:p.name,kind:p.kind,version:p.latest_version,description:p.description})));}
  else if(command==='install')await install(args[0]);
  else if(command==='uninstall'){
    const root=resolve('.'),cfg=await project(root),path=join(root,'threetopia-lock.json'),lock=await readJSON(path),p=lock.packages[args[0]];if(!p)throw Error('This package is not installed.');if(Object.entries(lock.packages).some(([n,p])=>n!==args[0]&&p.manifest.dependencies?.[args[0]]))throw Error('Another installed package depends on this package. Remove that package first.');
    await api(`/packages/${p.packageId}/install`,{method:'DELETE',body:{projectId:cfg.projectId}});await rm(within(root,p.directory),{recursive:true,force:true});delete lock.packages[args[0]];delete cfg.manifest.dependencies[args[0]];await writeFile(path,JSON.stringify(lock,null,2)+'\n');await writeFile(join(root,'threetopia.json'),JSON.stringify(cfg,null,2)+'\n');console.log(`Removed ${args[0]}. Copied assets are kept; review them before publishing.`);
  }else if(command==='use'){
    const root=resolve('.'),cfg=await project(root),lock=await readJSON(join(root,'threetopia-lock.json')),pkg=lock.packages[args[0]],role=opts.as;if(!pkg)throw Error('Install this package first.');if(cfg.manifest.kind!=='world'||!['world','map','overview'].includes(role))throw Error('Choose a world content role with --as world|map|overview.');const file=pkg.manifest.exports?.[opts.export];if(!file?.endsWith('.glb'))throw Error('Choose an exported GLB with --export name.');const data=await safeRead(root,`${pkg.directory}/${file}`);inspectGLB(data,role,await readJSON(join(root,'tile.lock.json')));const target=`content/${role}.glb`;await mkdir(dirname(within(root,target)),{recursive:true});await writeFile(within(root,target),data);cfg.manifest.content[role]=target;if(!cfg.files.includes(target))cfg.files.push(target);await writeFile(join(root,'threetopia.json'),JSON.stringify(cfg,null,2)+'\n');console.log(`Using ${args[0]} export ${opts.export} as ${role} content. Geometry fits the slot.`);
  }else{help();throw Error(`Unknown command: ${command}`);}
}catch(error){console.error(`Threetopia: ${error.message}`);process.exitCode=1;}
