import {readFile} from 'node:fs/promises';
import {entries,descriptions,name} from './package-layout.mjs';

const notes={
 core:'Start Engine before constructing GPU systems. Input attaches to the renderer canvas; the scene host owns the document, renderer and input listeners.',
 lighting:'Install materials and shadow hooks before compiling meshes. Local lights are populated from Village and BoatModel, then updated after the camera each frame.',
 sky:'Atmosphere must exist before Sky; Clouds feeds Sky, and Environment captures that sky into scene lighting. App updates the sun direction, shared uniforms and all four systems every frame.',
 terrain:'Village flattens its building pads into TerrainData first. Derive the shore field and TerrainGPU afterwards, then create Terrain and Rocks. Changing that order puts houses above or below the ground.',
 village:'Needs the shared TerrainData and Colliders. Its constructor flattens building pads; run this before TerrainGPU, terrain meshes, vegetation and reef generation.',
 vegetation:'Requires the finished village layout and its adjusted TerrainData. The group owns instanced palms, ferns and grass; update with the current camera for distance-dependent LODs.',
 ocean:'FFT runs on the WebGPU renderer. Surface, terrain, shore simulation, water material, water query and wake share the same simulation. The excerpt shows their initial connection; App.js also connects foam, caustics, shore waves and boat wakes.',
 reef:'Needs the completed shore field and adjusted TerrainData. Connect OceanFFT with setOcean so coral sway follows the same swell. Update receives delta seconds and the camera position.',
 wildlife:'Requires terrain, village, vegetation, colliders, water queries, boat and spray services. The flock/critter batches and behaviors are owned here; the reusable low-level gull geometry is a separate dependency.',
 whale:'Requires TerrainData, WaterQuery and Spray. Await whale.load() before presenting a ready scene. Original model, textures and attribution are included under assets/models/whale/.',
 debris:'Place after terrain, village, vegetation and rocks. Await debris.scanned.promise before claiming all assets are loaded. The original scanned meshes and credits are included under assets/models/debris/.',
 boat:'BoatModel owns the visible geometry; BoatController drives the model using water queries and collisions. BoatSpray connects the controller to the ocean spray service.',
 player:'Needs Input, camera, adjusted TerrainData, Colliders, WaterQuery, BoatController and Reef. The host updates either Player or FlyCamera, so two controllers never drive the camera at once.',
 postprocessing:'Requires the shared SceneRenderer attachments and the ocean/sky services. Underwater uses opaque depth plus the water mask; PostFX combines those with clouds and atmospheric haze.',
 audio:'Call resume from a click or other user gesture. Feed the audio mixer current player, boat, weather and water state each frame (see App._updateAudio). This package includes all 32 original recordings and their credits.',
 ui:'UI builds the controls; AppUI connects them to an initialized App. Load src/ui/ui.css and the locally bundled fonts. AppUI expects the original ocean, sky, camera, audio and post-processing services.',
};
const properties={lighting:['localLights'],sky:['atmosphere','sky','clouds','environment'],terrain:['terrainGPU','terrain','rocks'],village:['village'],vegetation:['vegetation'],ocean:['fft','surface','query'],reef:['reef'],wildlife:['wildlife'],whale:['whale'],debris:['debris'],boat:['boat','boatCtl','boatSpray'],player:['player'],postprocessing:['underwater','post']};
const settings={core:'Field of view and dynamic resolution',lighting:'Time of day, exposure and sun shadows',sky:'Time of day, cloud coverage and cirrus',terrain:'Terrain and rock visibility',village:'Village visibility and time of day',vegetation:'Vegetation visibility',ocean:'Wind speed, choppiness and surf amplitude',reef:'Reef visibility',wildlife:'Bird and beach wildlife visibility',whale:'Whale visibility',debris:'Debris visibility',boat:'Boat visibility',player:'Field of view and free camera speed',postprocessing:'Bloom, saturation and film grain',audio:'Master volume, mute and an explicit enable-audio button',ui:'Field of view and time controls, plus the complete original settings tabs',rocks:'Seed, count, geometry detail, exposure and wireframe',gulls:'Seed, count, animation speed, exposure and wireframe','map-tile':'Map/overview representation, exposure and wireframe','world-tile':'All original controls: ocean, surf, sky, camera, audio, quality and post-processing'};

async function compositionExcerpt(role){
 const source=await readFile(new URL('../../packages/components/tidewater-world-tile/src/App.js',import.meta.url),'utf8');
 const {parse}=await import('../../packages/platform/syntax.js');const ast=parse(source,{sourceType:'module'});
 const selected=[];
 function visit(node){if(!node||typeof node!=='object')return;if(node.type==='ExpressionStatement'&&node.expression.type==='AssignmentExpression'){const a=node.expression;if(a.left.object?.type==='ThisExpression'&&properties[role]?.includes(a.left.property.name)&&a.right.type==='NewExpression')selected.push(source.slice(node.start,node.end).replaceAll('\t','  ').replaceAll('this.','app.'));}for(const [key,value]of Object.entries(node))if(!['loc','start','end'].includes(key))if(Array.isArray(value))value.forEach(visit);else visit(value);}
 visit(ast);
 const body=selected.join('\n');
 const used=ast.program.body.filter(node=>node.type==='ImportDeclaration'&&node.specifiers.some(s=>new RegExp('\\b'+s.local.name+'\\b').test(body))).map(node=>source.slice(node.start,node.end)).join('\n');
 return used+'\n\n// Construction excerpt from App.init(), using its existing services.\n// app is the composition being initialized, not an already-running second scene.\nexport function attachComponent(app) {\n  const {scene, renderer, camera} = app;\n'+body.split('\n').map(line=>'  '+line).join('\n')+'\n}\n';
}
const custom={
 core:`import {Engine, Input} from '@dgreenheck/tidewater-core';\n\nconst engine = new Engine(document.getElementById('app'));\nawait engine.init();\nconst input = new Input(engine.renderer.domElement);\n// Pass engine.renderer, engine.scene and engine.camera to other systems.\n// The complete world host owns the render loop and document lifetime.`,
 audio:`import {SoundScape} from '@dgreenheck/tidewater-audio';\n\nconst sound = new SoundScape();\ndocument.querySelector('#enable-audio').onclick = () => sound.resume();\nsound.setMasterVolume(0.6);\nsound.setMuted(false);\n// Feed sound.update(deltaSeconds, sceneState) in your frame loop.\n// App._updateAudio supplies the complete sceneState contract.\n// When the scene is removed:\n// sound.dispose();`,
 ui:`import {UI, AppUI} from '@dgreenheck/tidewater-ui';\n\n// app has completed await app.init().\nexport function attachControls(app) {\n  const ui = new UI();\n  app.ui = new AppUI(app, ui);\n  ui.selectTab('ocean');\n  ui.togglePanel(true);\n  return ui;\n}\n// App.frame calls app.ui.update(deltaSeconds).`,
 rocks:`import {createRocks} from '@dgreenheck/tidewater-rocks';\n\nexport function addRocks(scene) {\n  const rocks = createRocks({seed:17, count:4, spread:7, detail:2});\n  scene.add(rocks.object);\n  console.log(rocks.inspect());\n  return () => rocks.dispose();\n}`,
 gulls:`import {createGulls} from '@dgreenheck/tidewater-gulls';\n\nexport function addGulls(scene) {\n  const gulls = createGulls({seed:17, count:7, height:[3.6,5.6]});\n  scene.add(gulls.object);\n  return {\n    update(elapsedSeconds) { gulls.update(elapsedSeconds); },\n    dispose() { gulls.dispose(); },\n  };\n}\n// update takes absolute elapsed seconds, not a frame delta.`,
 'map-tile':`import {createMapTile} from '@dgreenheck/tidewater-map-tile';\n\n// landmark is your loaded, decoded boat/pier Object3D.\nexport function addMapTile(scene, landmark) {\n  const tile = createMapTile({landmark, overview:false, seed:17});\n  scene.add(tile.object);\n  return {\n    update(elapsedSeconds) { tile.update(elapsedSeconds); },\n    dispose() { tile.dispose(); },\n  };\n}\n// The caller retains ownership of the landmark's geometry and materials.`,
};
const worldCode=`import {TerrainData} from '@dgreenheck/tidewater-terrain';\nimport {Colliders} from '@dgreenheck/tidewater-player';\nimport {Village} from '@dgreenheck/tidewater-village';\nimport {Vegetation} from '@dgreenheck/tidewater-vegetation';\nimport {BoatModel} from '@dgreenheck/tidewater-boat';\nimport {Reef} from '@dgreenheck/tidewater-reef';\nimport {OceanFFT} from '@dgreenheck/tidewater-ocean';\nimport {computeShoreField} from '@dgreenheck/tidewater-terrain/world/ShoreField.js';\nimport {WORLD} from '@dgreenheck/tidewater-core';\n\n// The island assembly inside the full world's initialization.\n// scene and renderer come from tidewater-core's initialized Engine.\nexport function assembleIsland({scene, renderer}) {\n  const terrainData = new TerrainData();\n  const colliders = new Colliders();\n  // Village adjusts the heightmap before terrain-derived data is built.\n  const village = new Village({scene, terrain:terrainData, colliders});\n  const vegetation = new Vegetation({scene, terrain:terrainData, village});\n  const shoreField = computeShoreField(terrainData, {\n    res:512, swellDir:[WORLD.swellDir.x, WORLD.swellDir.y],\n  });\n  const reef = new Reef({scene, terrain:terrainData, shoreField});\n  const fft = new OceanFFT(renderer);\n  reef.setOcean(fft);\n  const boat = new BoatModel();\n  scene.add(boat.group);\n  boat.group.position.copy(WORLD.boatDock.position);\n  boat.group.rotation.y = WORLD.boatDock.heading;\n  return {terrainData, colliders, village, vegetation, shoreField, reef, fft, boat};\n}\n// src/App.js supplies the remaining sky, terrain, water rendering, physics,\n// wildlife, audio and post-processing stages plus their ordered frame updates.`;
export async function packageReadme(role,dependencies=[]){
 const title=name(role),description=descriptions[role]||({rocks:'Procedural fracture geometry and a scene-independent rock factory',gulls:'Animated gull geometry and a scene-independent flock factory','map-tile':'Lightweight map composition of the boat/pier landmark, rocks, gulls and palm'})[role];
 const standalone=['rocks','gulls','map-tile'].includes(role);
 let text=`# ${title}\n\n${description}. Version 0.1.0.\n\nOriginal Tidewater by **Dan Greenheck (@dgreenheck)**, pinned to revision \`d32799fcd85b79fb2fde3c4254f9d3805edecee3\`. Initially maintained in the Threetopia registry by **@promontis**, pending an account transfer. The \`@dgreenheck/\` package names and imports stay stable. This is attribution, not a claim that Dan published this conversion himself.\n\n## Install\n\n\`\`\`sh\nthreetopia install ${title}@0.1.0\n\`\`\`\n\nThe CLI downloads verified files and exact dependencies to \`threetopia_modules/dgreenheck/\`. These are Threetopia registry packages. Point your bundler's package aliases at those directories to use the scoped imports below; supply Three.js 0.186.0 once for the whole scene. The repository workspace already configures those links.\n\n## Use in code\n\n${notes[role]||''}\n\n\`\`\`js\n${role==='world-tile'?worldCode:custom[role]||await compositionExcerpt(role)}\n\`\`\`\n`;
 if(role==='world-tile')text+=`\nFor the complete scene, use the supplied composition (the code above illustrates one stage):\n\n\`\`\`js\nimport '@dgreenheck/tidewater-core/core/TSLPatches.js';\nimport {App} from '@dgreenheck/tidewater-world-tile';\nimport {UI, AppUI} from '@dgreenheck/tidewater-ui';\n\nconst app = new App(); // requires a dedicated document with <div id="app">\nawait app.init();\nawait app.debris.scanned.promise;\nconst ui = new UI();\napp.ui = new AppUI(app, ui);\napp.start();\n// The packaged entry.js adds loading, audio activation, readiness and cleanup.\n\`\`\`\n\nInitialization: core → sky/lighting → terrain data → village → vegetation → derived terrain/rocks/debris → reef/boat → ocean → player/wildlife/whale → post-processing/audio/UI. Each frame updates physics, camera, sky, ocean, LODs, wildlife, lights, post-processing and audio in that order. See the shipped \`src/App.js\`, \`entry.js\` and \`package-graph.json\` for the complete code and dependency graph.\n\nThe world owns one immutable reserved host tile, three static world/map/overview representations, and the full playable scene runtime. The static representations come from \`tidewater-map-tile\`; the full original renderer runs in its own sandboxed document.\n`;
 if(role==='map-tile')text+=`\nThe composition imports \`createRocks\` from \`tidewater-rocks\`, \`createGulls\` from \`tidewater-gulls\`, and \`buildPalmFar\` from \`tidewater-vegetation\`. In \`index.js\`, those components are added to the same group as the cloned boat/pier landmark. Its update forwards absolute time to the gulls, and dispose releases only generated components. The \`source\` export exposes terrain, village, boat and collision classes for baking the original landmark.\n\n\`map.glb\` and \`overview.glb\` are validated, ordinary uncompressed static GLBs. The preview displays these published exports; it does not rerun landmark generation.\n`;
 text+=`\n## Dependencies\n\n${dependencies.length?dependencies.map(dep=>`- \`${dep}@0.1.0\``).join('\n'):'- Three.js peer dependency; no other Tidewater packages.'}\n\nDependencies above are executable imports, not just catalog links. \`package.json\` declares exact published versions; \`threetopia-lock.json\` records the downloaded file hashes.\n\n## Preview and settings\n\nClone this package from your own account, or run \`threetopia preview\` from its prepared project directory. Its registry page also contains the preview. ${role==='world-tile'?'The complete scene requires WebGPU and retains the original settings and gameplay.':standalone?'The standalone WebGL preview needs no full-world initialization.':'The preview opens this component **in the complete Tidewater scene**, with its own component settings tab. It requires WebGPU; the rest of the scene remains present to supply lighting, terrain, water and gameplay context. It is not an isolated subsystem benchmark.'}\n\nSettings: **${settings[role]}**. ${!standalone&&role!=='world-tile'?'The exact-version preview reference points to `@dgreenheck/tidewater-world-tile@0.1.0`; this is a presentation link, not an installation dependency, so it creates no circular package dependency. Local contextual previews need registry access.':''}\n\n## Ownership and cleanup\n\n${standalone?'Factories return instance-owned objects. Call dispose() when removing an instance. Rocks and gulls never create a renderer, timers or DOM listeners. The map factory also preserves caller-owned landmark resources.':'These extracted systems share the original Tidewater shader context and constructor contracts. Compose them within one scene document. Some systems do not expose standalone disposal; the world host stops the animation loop, disposes audio/GPU resources and destroys its isolated document. Separate playable worlds use separate documents.'}\n\n## Source, licenses and checks\n\nMIT code; preserve \`LICENSE\` and \`PROVENANCE.json\`. Audio, scans, whale assets and fonts retain their included credits and licenses. The complete pinned source and resource inventory is recorded in the world's \`coverage.json\` and \`source.json.gz\`.\n\nRun \`threetopia check\` before \`threetopia push\` and \`threetopia publish\`. Repository checks verify all 130 original source files, unchanged implementations apart from package imports, dependency closure, geometry budgets, checksums and the complete scene's gameplay lifecycle. The settings previews have separate browser checks.\n`;
 return text;
}
